management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: configprops,env,health,info
  info:
    os:
      enabled: true
    java:
      enabled: true
    git:
      mode: full

spring:
  main:
    banner-mode: off
  application:
    name: Client A
server:
  # Use same port as govsso-session/docker-compose.yml.
  port: 11443
  ssl:
    enabled: true
    key-store-password: changeit
    key-store: classpath:clienta.localhost.keystore.p12
    key-store-type: PKCS12

govsso:
  post-logout-redirect-uri: https://clienta.localhost:11443/?show-post-logout-message
  client-id: client-a
  client-secret: secreta
  authorization-grant-type: authorization_code
  redirect-uri: 'https://clienta.localhost:11443/login/oauth2/code/govsso'
  scope: openid
  issuer-uri: https://gateway.localhost:13443/
  trust-store: classpath:clienta.localhost.truststore.p12
  trust-store-password: changeit

example-client:
  logo: client-a.svg
  session:
    idle-timeout: PT40M
